# -*- coding: utf-8 -*-
"""
Created on Sun Apr  8 09:45:29 2018

@author: abaena
"""

DATATYPE_AGENT = 'agent'

DATATYPE_PATH_METRICS = 'pathmet'
DATATYPE_LOG_EVENTS = 'logeve'
DATATYPE_LOG_METRICS = 'logmet'

DATATYPE_MONITOR_HOST = 'host'
DATATYPE_MONITOR_MICROSERVICE = 'ms'
DATATYPE_MONITOR_TOMCAT = 'tomc'
DATATYPE_MONITOR_POSTGRES = 'psql'

SOURCE_TYPE_READER = "reader"
SOURCE_TYPE_HOST = "host"
SOURCE_TYPE_SPRINGMICROSERVICE = "spring_microservice"
SOURCE_TYPE_TOMCAT = "tomcat"
SOURCE_TYPE_POSTGRES = "postgres"

MEASURE_CAT_METRIC=0
MEASURE_CAT_EVENT=1
